# FHFA Home Price Index

In [1]:
import pandas as pd

In [2]:
file = "../Data/FHFA/HPI_master.csv"
data = pd.read_csv(file)

In [3]:
data.head(12)

,hpi_type,hpi_flavor,frequency,level,place_name,place_id,yr,period,index_nsa,index_sa
0,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,1,100.00,100.00
1,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,2,100.99,101.07
2,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,3,101.36,101.00
3,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,4,101.74,101.04
4,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,5,102.38,101.43
5,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,6,102.81,101.56
6,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,7,103.02,101.94
7,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,8,103.18,102.13
8,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,9,102.86,102.06
9,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,10,103.09,102.41
10,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,11,103.99,103.37
11,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,12,103.75,103.45

In [4]:
data.rename(columns={'yr':'Year','period':'Month'}, inplace=True)

In [5]:
data.head()

,hpi_type,hpi_flavor,frequency,level,place_name,place_id,Year,Month,index_nsa,index_sa
0,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,1,100.00,100.00
1,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,2,100.99,101.07
2,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,3,101.36,101.00
3,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,4,101.74,101.04
4,traditional,purchase-only,monthly,USA or Census Division,East North Central Division,DV_ENC,1991,5,102.38,101.43

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107988 entries, 0 to 107987
Data columns (total 10 columns):
hpi_type      107988 non-null object
hpi_flavor    107988 non-null object
frequency     107988 non-null object
level         107988 non-null object
place_name    107988 non-null object
place_id      107988 non-null object
Year          107988 non-null int64
Month         107988 non-null int64
index_nsa     107986 non-null float64
index_sa      35284 non-null float64
dtypes: float64(2), int64(2), object(6)
memory usage: 8.2+ MB

In [8]:
data['Month'] = data['Month'].apply(str)

In [9]:
data['Month'] = data['Month'].map({'1':'January', 
                                '2':'February',
                                '3':'March',
                                '4':'April',
                                '5':'May',
                                '6':'June',
                                '7':'July',
                                '8':'August',
                                '9':'September',
                                '10':'October',
                                '11':'November',
                                '12':'December',
                                })

In [12]:
data.hpi_type.unique()

array(['traditional', 'non-metro', 'distress-free', 'developmental'],
      dtype=object)

In [13]:
data.hpi_flavor.unique()

array(['purchase-only', 'all-transactions', 'expanded-data'], dtype=object)

In [14]:
data.frequency.unique()

array(['monthly', 'quarterly'], dtype=object)

In [15]:
data.place_name.unique()

array(['East North Central Division', 'East South Central Division',
       'Middle Atlantic Division', 'Mountain Division',
       'New England Division', 'Pacific Division',
       'South Atlantic Division', 'West North Central Division',
       'West South Central Division', 'United States', 'Abilene, TX',
       'Akron, OH', 'Albany, GA', 'Albany-Lebanon, OR',
       'Albany-Schenectady-Troy, NY', 'Albuquerque, NM', 'Alexandria, LA',
       'Allentown-Bethlehem-Easton, PA-NJ', 'Altoona, PA', 'Amarillo, TX',
       'Ames, IA', 'Anaheim-Santa Ana-Irvine, CA (MSAD)', 'Anchorage, AK',
       'Ann Arbor, MI', 'Anniston-Oxford, AL', 'Appleton, WI',
       'Asheville, NC', 'Athens-Clarke County, GA',
       'Atlanta-Sandy Springs-Alpharetta, GA',
       'Atlantic City-Hammonton, NJ', 'Auburn-Opelika, AL',
       'Augusta-Richmond County, GA-SC',
       'Austin-Round Rock-Georgetown, TX', 'Bakersfield, CA',
       'Baltimore-Columbia-Towson, MD', 'Bangor, ME',
       'Barnstable Town, MA', 'Baton Rouge, LA', 'Battle Creek, MI',
       'Bay City, MI', 'Beaumont-Port Arthur, TX', 'Beckley, WV',
       'Bellingham, WA', 'Bend, OR', 'Billings, MT', 'Binghamton, NY',
       'Birmingham-Hoover, AL', 'Bismarck, ND',
       'Blacksburg-Christiansburg, VA', 'Bloomington, IL',
       'Bloomington, IN', 'Bloomsburg-Berwick, PA', 'Boise City, ID',
       'Boston, MA (MSAD)', 'Boulder, CO', 'Bowling Green, KY',
       'Bremerton-Silverdale-Port Orchard, WA',
       'Bridgeport-Stamford-Norwalk, CT', 'Brownsville-Harlingen, TX',
       'Brunswick, GA', 'Buffalo-Cheektowaga, NY', 'Burlington, NC',
       'Burlington-South Burlington, VT', 'California-Lexington Park, MD',
       'Cambridge-Newton-Framingham, MA (MSAD)', 'Camden, NJ (MSAD)',
       'Canton-Massillon, OH', 'Cape Coral-Fort Myers, FL',
       'Cape Girardeau, MO-IL', 'Carbondale-Marion, IL',
       'Carson City, NV', 'Casper, WY', 'Cedar Rapids, IA',
       'Chambersburg-Waynesboro, PA', 'Champaign-Urbana, IL',
       'Charleston, WV', 'Charleston-North Charleston, SC',
       'Charlotte-Concord-Gastonia, NC-SC', 'Charlottesville, VA',
       'Chattanooga, TN-GA', 'Cheyenne, WY',
       'Chicago-Naperville-Evanston, IL (MSAD)', 'Chico, CA',
       'Cincinnati, OH-KY-IN', 'Clarksville, TN-KY', 'Cleveland, TN',
       'Cleveland-Elyria, OH', "Coeur d'Alene, ID",
       'College Station-Bryan, TX', 'Colorado Springs, CO',
       'Columbia, MO', 'Columbia, SC', 'Columbus, GA-AL', 'Columbus, IN',
       'Columbus, OH', 'Corpus Christi, TX', 'Corvallis, OR',
       'Crestview-Fort Walton Beach-Destin, FL', 'Cumberland, MD-WV',
       'Dallas-Plano-Irving, TX (MSAD)', 'Dalton, GA', 'Danville, IL',
       'Daphne-Fairhope-Foley, AL', 'Davenport-Moline-Rock Island, IA-IL',
       'Dayton-Kettering, OH', 'Decatur, AL', 'Decatur, IL',
       'Deltona-Daytona Beach-Ormond Beach, FL',
       'Denver-Aurora-Lakewood, CO', 'Des Moines-West Des Moines, IA',
       'Detroit-Dearborn-Livonia, MI (MSAD)', 'Dothan, AL', 'Dover, DE',
       'Dubuque, IA', 'Duluth, MN-WI', 'Durham-Chapel Hill, NC',
       'East Stroudsburg, PA', 'Eau Claire, WI', 'El Centro, CA',
       'Elgin, IL (MSAD)', 'Elizabethtown-Fort Knox, KY',
       'Elkhart-Goshen, IN', 'Elmira, NY', 'El Paso, TX', 'Enid, OK',
       'Erie, PA', 'Eugene-Springfield, OR', 'Evansville, IN-KY',
       'Fairbanks, AK', 'Fargo, ND-MN', 'Farmington, NM',
       'Fayetteville, NC', 'Fayetteville-Springdale-Rogers, AR',
       'Flagstaff, AZ', 'Flint, MI', 'Florence, SC',
       'Florence-Muscle Shoals, AL', 'Fond du Lac, WI',
       'Fort Collins, CO',
       'Fort Lauderdale-Pompano Beach-Sunrise, FL (MSAD)',
       'Fort Smith, AR-OK', 'Fort Wayne, IN',
       'Fort Worth-Arlington-Grapevine, TX (MSAD)',
       'Frederick-Gaithersburg-Rockville, MD (MSAD)', 'Fresno, CA',
       'Gadsden, AL', 'Gainesville, FL', 'Gainesville, GA',
       'Gary, IN (MSAD)', 'Gettysburg, PA', 'Glens Falls, NY',
       'Goldsboro, NC', 'Grand Forks, ND-MN', 'Grand Island, NE',
       'Grand Junction, CO', 'Grand Rapids-Kentwood, MI',
       'Grants Pass, OR', 'Great Falls, MT', 'Greeley, CO',
       'Green Bay, WI', 'Greensboro-High Point, NC', 'Greenville, NC',
       'Greenville-Anderson, SC', 'Gulfport-Biloxi, MS',
       'Hagerstown-Martinsburg, MD-WV', 'Hammond, LA',
       'Hanford-Corcoran, CA', 'Harrisburg-Carlisle, PA',
       'Harrisonburg, VA', 'Hartford-East Hartford-Middletown, CT',
       'Hattiesburg, MS', 'Hickory-Lenoir-Morganton, NC',
       'Hilton Head Island-Bluffton, SC', 'Hinesville, GA',
       'Homosassa Springs, FL', 'Hot Springs, AR', 'Houma-Thibodaux, LA',
       'Houston-The Woodlands-Sugar Land, TX',
       'Huntington-Ashland, WV-KY-OH', 'Huntsville, AL',
       'Idaho Falls, ID', 'Indianapolis-Carmel-Anderson, IN',
       'Iowa City, IA', 'Ithaca, NY', 'Jackson, MI', 'Jackson, MS',
       'Jackson, TN', 'Jacksonville, FL', 'Jacksonville, NC',
       'Janesville-Beloit, WI', 'Jefferson City, MO', 'Johnson City, TN',
       'Johnstown, PA', 'Jonesboro, AR', 'Joplin, MO',
       'Kahului-Wailuku-Lahaina, HI', 'Kalamazoo-Portage, MI',
       'Kankakee, IL', 'Kansas City, MO-KS', 'Kennewick-Richland, WA',
       'Killeen-Temple, TX', 'Kingsport-Bristol, TN-VA', 'Kingston, NY',
       'Knoxville, TN', 'Kokomo, IN', 'La Crosse-Onalaska, WI-MN',
       'Lafayette, LA', 'Lafayette-West Lafayette, IN',
       'Lake Charles, LA', 'Lake County-Kenosha County, IL-WI (MSAD)',
       'Lake Havasu City-Kingman, AZ', 'Lakeland-Winter Haven, FL',
       'Lancaster, PA', 'Lansing-East Lansing, MI', 'Laredo, TX',
       'Las Cruces, NM', 'Las Vegas-Henderson-Paradise, NV',
       'Lawrence, KS', 'Lawton, OK', 'Lebanon, PA', 'Lewiston, ID-WA',
       'Lewiston-Auburn, ME', 'Lexington-Fayette, KY', 'Lima, OH',
       'Lincoln, NE', 'Little Rock-North Little Rock-Conway, AR',
       'Logan, UT-ID', 'Longview, TX', 'Longview, WA',
       'Los Angeles-Long Beach-Glendale, CA (MSAD)',
       'Louisville/Jefferson County, KY-IN', 'Lubbock, TX',
       'Lynchburg, VA', 'Macon-Bibb County, GA', 'Madera, CA',
       'Madison, WI', 'Manchester-Nashua, NH', 'Manhattan, KS',
       'Mankato, MN', 'Mansfield, OH', 'McAllen-Edinburg-Mission, TX',
       'Medford, OR', 'Memphis, TN-MS-AR', 'Merced, CA',
       'Miami-Miami Beach-Kendall, FL (MSAD)',
       'Michigan City-La Porte, IN', 'Midland, MI', 'Midland, TX',
       'Milwaukee-Waukesha, WI',
       'Minneapolis-St. Paul-Bloomington, MN-WI', 'Missoula, MT',
       'Mobile, AL', 'Modesto, CA', 'Monroe, LA', 'Monroe, MI',
       'Montgomery, AL',
       'Montgomery County-Bucks County-Chester County, PA (MSAD)',
       'Morgantown, WV', 'Morristown, TN', 'Mount Vernon-Anacortes, WA',
       'Muncie, IN', 'Muskegon, MI',
       'Myrtle Beach-Conway-North Myrtle Beach, SC-NC', 'Napa, CA',
       'Naples-Marco Island, FL',
       'Nashville-Davidson--Murfreesboro--Franklin, TN',
       'Nassau County-Suffolk County, NY (MSAD)', 'Newark, NJ-PA (MSAD)',
       'New Bern, NC', 'New Brunswick-Lakewood, NJ (MSAD)',
       'New Haven-Milford, CT', 'New Orleans-Metairie, LA',
       'New York-Jersey City-White Plains, NY-NJ (MSAD)', 'Niles, MI',
       'North Port-Sarasota-Bradenton, FL', 'Norwich-New London, CT',
       'Oakland-Berkeley-Livermore, CA (MSAD)', 'Ocala, FL',
       'Ocean City, NJ', 'Odessa, TX', 'Ogden-Clearfield, UT',
       'Oklahoma City, OK', 'Olympia-Lacey-Tumwater, WA',
       'Omaha-Council Bluffs, NE-IA', 'Orlando-Kissimmee-Sanford, FL',
       'Oshkosh-Neenah, WI', 'Owensboro, KY',
       'Oxnard-Thousand Oaks-Ventura, CA',
       'Palm Bay-Melbourne-Titusville, FL', 'Panama City, FL',
       'Parkersburg-Vienna, WV', 'Pensacola-Ferry Pass-Brent, FL',
       'Peoria, IL', 'Philadelphia, PA (MSAD)',
       'Phoenix-Mesa-Chandler, AZ', 'Pine Bluff, AR', 'Pittsburgh, PA',
       'Pittsfield, MA', 'Pocatello, ID', 'Portland-South Portland, ME',
       'Portland-Vancouver-Hillsboro, OR-WA', 'Port St. Lucie, FL',
       'Poughkeepsie-Newburgh-Middletown, NY',
       'Prescott Valley-Prescott, AZ', 'Providence-Warwick, RI-MA',
       'Provo-Orem, UT', 'Pueblo, CO', 'Punta Gorda, FL', 'Racine, WI',
       'Raleigh-Cary, NC', 'Rapid City, SD', 'Reading, PA', 'Redding, CA',
       'Reno, NV', 'Richmond, VA', 'Riverside-San Bernardino-Ontario, CA',
       'Roanoke, VA', 'Rochester, MN', 'Rochester, NY', 'Rockford, IL',
       'Rockingham County-Strafford County, NH (MSAD)', 'Rocky Mount, NC',
       'Rome, GA', 'Sacramento-Roseville-Folsom, CA', 'Saginaw, MI',
       'St. Cloud, MN', 'St. George, UT', 'St. Joseph, MO-KS',
       'St. Louis, MO-IL', 'Salem, OR', 'Salinas, CA', 'Salisbury, MD-DE',
       'Salt Lake City, UT', 'San Angelo, TX',
       'San Antonio-New Braunfels, TX',
       'San Diego-Chula Vista-Carlsbad, CA',
       'San Francisco-San Mateo-Redwood City, CA (MSAD)',
       'San Jose-Sunnyvale-Santa Clara, CA',
       'San Luis Obispo-Paso Robles, CA', 'San Rafael, CA (MSAD)',
       'Santa Cruz-Watsonville, CA', 'Santa Fe, NM',
       'Santa Maria-Santa Barbara, CA', 'Santa Rosa-Petaluma, CA',
       'Savannah, GA', 'Scranton--Wilkes-Barre, PA',
       'Seattle-Bellevue-Kent, WA (MSAD)', 'Sebastian-Vero Beach, FL',
       'Sebring-Avon Park, FL', 'Sheboygan, WI', 'Sherman-Denison, TX',
       'Shreveport-Bossier City, LA', 'Sierra Vista-Douglas, AZ',
       'Sioux City, IA-NE-SD', 'Sioux Falls, SD',
       'South Bend-Mishawaka, IN-MI', 'Spartanburg, SC',
       'Spokane-Spokane Valley, WA', 'Springfield, IL', 'Springfield, MA',
       'Springfield, MO', 'Springfield, OH', 'State College, PA',
       'Staunton, VA', 'Stockton, CA', 'Sumter, SC', 'Syracuse, NY',
       'Tacoma-Lakewood, WA (MSAD)', 'Tallahassee, FL',
       'Tampa-St. Petersburg-Clearwater, FL', 'Terre Haute, IN',
       'Texarkana, TX-AR', 'The Villages, FL', 'Toledo, OH', 'Topeka, KS',
       'Trenton-Princeton, NJ', 'Tucson, AZ', 'Tulsa, OK',
       'Tuscaloosa, AL', 'Twin Falls, ID', 'Tyler, TX',
       'Urban Honolulu, HI', 'Utica-Rome, NY', 'Valdosta, GA',
       'Vallejo, CA', 'Victoria, TX', 'Vineland-Bridgeton, NJ',
       'Virginia Beach-Norfolk-Newport News, VA-NC', 'Visalia, CA',
       'Waco, TX', 'Walla Walla, WA', 'Warner Robins, GA',
       'Warren-Troy-Farmington Hills, MI (MSAD)',
       'Washington-Arlington-Alexandria, DC-VA-MD-WV (MSAD)',
       'Waterloo-Cedar Falls, IA', 'Watertown-Fort Drum, NY',
       'Wausau-Weston, WI', 'Weirton-Steubenville, WV-OH',
       'Wenatchee, WA',
       'West Palm Beach-Boca Raton-Boynton Beach, FL (MSAD)',
       'Wheeling, WV-OH', 'Wichita, KS', 'Wichita Falls, TX',
       'Williamsport, PA', 'Wilmington, DE-MD-NJ (MSAD)',
       'Wilmington, NC', 'Winchester, VA-WV', 'Winston-Salem, NC',
       'Worcester, MA-CT', 'Yakima, WA', 'York-Hanover, PA',
       'Youngstown-Warren-Boardman, OH-PA', 'Yuba City, CA', 'Yuma, AZ',
       'Alaska', 'Alabama', 'Arkansas', 'Arizona', 'California',
       'Colorado', 'Connecticut', 'District of Columbia', 'Delaware',
       'Florida', 'Georgia', 'Hawaii', 'Iowa', 'Idaho', 'Illinois',
       'Indiana', 'Kansas', 'Kentucky', 'Louisiana', 'Massachusetts',
       'Maryland', 'Maine', 'Michigan', 'Minnesota', 'Missouri',
       'Mississippi', 'Montana', 'North Carolina', 'North Dakota',
       'Nebraska', 'New Hampshire', 'New Jersey', 'New Mexico', 'Nevada',
       'New York', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Virginia', 'Vermont', 'Washington', 'Wisconsin',
       'West Virginia', 'Wyoming', 'Puerto Rico'], dtype=object)

In [16]:
data.level.unique()

array(['USA or Census Division', 'MSA', 'State', 'Puerto Rico'],
      dtype=object)

# TBD
Figure how whether to split or aggregate the dataframe above.