
# FHFA Home Price Index

Source: Federal Housing Finance Agency House Price Index (HPI), Purchase-only, Monthly Historical  

Links:
 - https://www.fhfa.gov/DataTools/Downloads/Pages/House-Price-Index.aspx
 - https://www.fhfa.gov/Media/PublicAffairs/Pages/House-Price-Index-Frequently-Asked-Questions.aspx

In [3]:
import pandas as pd

In [4]:
#file = "../Data/FHFA/HPI_PO_monthly_hist.xls"
url = "https://storage.api.eriscape.com/v1/AUTH_andrew/laughing-umbrella/Data/FHFA/HPI_PO_monthly_hist.xls"
data = pd.read_excel(url, header=2)

In [5]:
data.head(5)

,Month,East North Central (NSA),East North Central (SA),East South Central (NSA),East South Central (SA),Middle Atlantic (NSA),Middle Atlantic (SA),Mountain (NSA),Mountain (SA),New England (NSA),...,Pacific (NSA),Pacific (SA),South Atlantic (NSA),South Atlantic (SA),West North Central (NSA),West North Central (SA),West South Central (NSA),West South Central (SA),USA (NSA),USA (SA)
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1991-01-01,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
2,1991-02-01,100.99,101.07,100.85,100.41,100.00,100.17,98.44,98.63,101.91,...,100.22,100.52,100.54,100.41,100.63,100.70,99.93,99.72,100.42,100.46
3,1991-03-01,101.36,101.00,101.01,100.60,99.91,99.74,100.15,100.54,101.70,...,100.00,100.13,101.01,100.60,100.42,100.14,100.82,100.55,100.72,100.50
4,1991-04-01,101.74,101.04,100.88,100.58,99.37,99.07,100.45,100.35,101.06,...,100.17,100.06,100.97,100.48,100.92,100.46,100.42,100.09,100.71,100.33

In [6]:
#Remove "non-seasonally adjusted" columns, identified by "(NSA)" in the name.
df = data[data.columns.drop(list(data.filter(regex='NSA')))]

In [7]:
df = df.drop(0)

In [8]:
# Extract Year/Month from Period
df.rename(columns={'Month':'Period'}, inplace=True)
df['Year'] = df['Period'].dt.year
df['Month'] = df['Period'].dt.month

In [9]:
df.head()

,Period,East North Central (SA),East South Central (SA),Middle Atlantic (SA),Mountain (SA),New England (SA),Pacific (SA),South Atlantic (SA),West North Central (SA),West South Central (SA),USA (SA),Year,Month
1,1991-01-01,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,1991,1
2,1991-02-01,101.07,100.41,100.17,98.63,102.55,100.52,100.41,100.70,99.72,100.46,1991,2
3,1991-03-01,101.00,100.60,99.74,100.54,101.44,100.13,100.60,100.14,100.55,100.50,1991,3
4,1991-04-01,101.04,100.58,99.07,100.35,100.94,100.06,100.48,100.46,100.09,100.33,1991,4
5,1991-05-01,101.43,100.77,99.12,100.39,99.81,100.11,100.57,100.24,100.35,100.41,1991,5

In [10]:
df = df.drop(columns=['Period'])

In [11]:
df['Month'] = df['Month'].apply(str)

In [12]:
df['Month'] = df['Month'].map({'1':'January', 
                                '2':'February',
                                '3':'March',
                                '4':'April',
                                '5':'May',
                                '6':'June',
                                '7':'July',
                                '8':'August',
                                '9':'September',
                                '10':'October',
                                '11':'November',
                                '12':'December',
                                })

In [13]:
df

,East North Central (SA),East South Central (SA),Middle Atlantic (SA),Mountain (SA),New England (SA),Pacific (SA),South Atlantic (SA),West North Central (SA),West South Central (SA),USA (SA),Year,Month
1,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,1991,January
2,101.07,100.41,100.17,98.63,102.55,100.52,100.41,100.70,99.72,100.46,1991,February
3,101.00,100.60,99.74,100.54,101.44,100.13,100.60,100.14,100.55,100.50,1991,March
4,101.04,100.58,99.07,100.35,100.94,100.06,100.48,100.46,100.09,100.33,1991,April
5,101.43,100.77,99.12,100.39,99.81,100.11,100.57,100.24,100.35,100.41,1991,May
6,101.56,101.56,98.82,101.46,98.68,99.88,100.67,100.59,100.96,100.54,1991,June
7,101.94,101.57,99.06,101.27,98.76,99.85,100.47,100.46,100.83,100.56,1991,July
8,102.13,100.76,98.60,101.30,98.01,99.95,100.03,100.78,100.57,100.38,1991,August
9,102.06,101.18,99.25,101.55,99.15,99.63,100.11,100.90,101.46,100.64,1991,September
10,102.41,101.65,98.97,102.52,98.75,100.34,100.95,101.54,100.67,100.95,1991,October
11,103.37,102.37,100.05,103.82,97.45,100.60,101.33,101.59,101.35,101.49,1991,November
12,103.45,103.29,100.31,103.42,98.72,100.66,101.58,102.67,101.86,101.85,1991,December
13,103.95,103.35,100.70,104.41,99.85,100.97,101.91,102.48,102.40,102.26,1992,January
14,104.48,104.26,101.94,105.30,100.48,101.39,102.69,103.11,103.28,103.01,1992,February
15,105.21,103.99,101.18,106.01,99.44,100.79,102.33,103.68,102.51,102.82,1992,March
16,105.28,103.55,100.80,105.67,98.40,100.28,101.81,103.69,102.78,102.55,1992,April
17,105.64,104.02,100.36,106.29,97.60,100.25,102.05,103.95,102.62,102.63,1992,May
18,105.69,104.25,100.30,106.90,96.52,99.73,101.85,104.37,103.01,102.60,1992,June
19,106.04,104.92,100.26,107.18,96.77,100.01,102.27,104.82,103.28,102.91,1992,July
20,106.50,105.47,100.28,108.02,97.74,100.17,103.07,105.00,104.03,103.40,1992,August
21,106.79,106.01,101.20,108.41,97.65,100.26,103.59,105.56,104.19,103.79,1992,September
22,107.51,106.65,101.37,109.40,98.05,99.57,103.73,105.77,104.92,104.09,1992,October
23,107.91,106.40,102.12,110.07,98.55,99.64,103.53,106.15,105.62,104.39,1992,November
24,108.53,106.85,101.26,111.23,97.45,99.24,103.30,106.43,105.10,104.29,1992,December
25,108.62,107.10,100.91,112.00,96.69,98.73,103.37,107.48,105.38,104.34,1993,January
26,108.43,106.60,100.75,112.23,95.37,98.06,103.22,107.94,105.53,104.12,1993,February
27,108.98,108.07,100.64,112.53,95.45,98.32,103.76,106.97,106.16,104.46,1993,March
28,109.56,108.40,101.39,113.91,96.52,98.30,104.55,108.42,106.59,105.12,1993,April
29,109.91,108.87,101.69,114.79,96.16,97.91,104.51,109.07,107.06,105.32,1993,May
30,110.61,108.99,101.49,115.48,96.94,97.94,105.09,109.59,107.60,105.72,1993,June
...,...,...,...,...,...,...,...,...,...,...,...,...
309,196.32,216.57,215.58,304.08,226.53,267.84,237.67,236.73,251.34,235.52,2016,September
310,197.16,217.01,216.42,307.77,228.30,268.88,239.34,237.83,252.52,236.79,2016,October
311,198.12,219.07,218.68,308.51,229.52,271.33,240.43,238.98,253.62,238.23,2016,November
312,199.61,220.95,217.94,311.02,229.46,272.58,241.81,240.88,254.42,239.40,2016,December
313,199.55,219.04,218.13,310.97,230.58,273.89,242.35,239.94,255.72,239.66,2017,January
314,201.17,222.35,220.36,315.52,232.81,275.98,243.61,241.63,257.70,241.72,2017,February
315,202.79,223.91,220.12,317.04,234.46,278.86,245.12,243.71,257.21,243.05,2017,March
316,203.34,223.05,222.58,319.94,235.04,280.88,247.60,244.05,261.04,244.79,2017,April
317,203.85,223.73,222.28,321.29,234.83,283.41,248.20,246.03,262.83,245.77,2017,May
318,203.70,225.62,222.63,323.12,236.10,285.36,248.63,246.91,262.79,246.48,2017,June
319,205.63,227.54,224.42,326.07,237.76,285.33,250.63,246.89,264.09,248.00,2017,July
320,206.62,228.53,226.09,327.75,238.27,289.51,253.06,248.12,265.90,249.88,2017,August
321,207.73,228.31,227.44,330.85,239.14,291.34,253.21,249.77,267.41,251.02,2017,September
322,209.10,233.42,229.33,333.82,241.73,293.14,255.14,251.28,268.59,253.04,2017,October
323,210.33,230.26,229.14,338.10,241.93,295.43,256.82,252.72,270.97,254.29,2017,November
324,212.23,232.21,229.93,340.05,243.64,297.05,258.57,252.91,272.15,255.80,2017,December
325,214.18,234.29,231.30,342.82,244.75,300.72,261.20,256.24,270.50,257.74,2018,January
326,214.99,235.91,232.46,345.68,247.83,304.07,263.23,257.28,276.73,260.09,2018,February
327,215.27,235.65,236.38,348.32,245.87,303.95,264.04,258.77,274.79,260.67,2018,March
328,217.38,236.30,234.77,349.88,247.85,305.20,265.45,259.45,274.55,261.59,2018,April
329,216.80,238.93,234.88,352.21,249.00,305.59,266.87,260.61,276.95,262.58,2018,May
330,218.29,241.22,236.38,355.85,249.15,307.12,266.19,262.34,277.34,263.68,2018,June
331,219.36,240.96,237.51,355.49,249.07,308.82,269.05,263.45,277.73,264.87,2018,July
332,220.21,242.32,236.87,358.27,250.86,310.76,270.93,264.27,279.34,266.18,2018,August
333,221.81,242.64,237.78,362.62,251.75,308.92,271.75,264.03,280.25,266.95,2018,September
334,223.02,245.27,237.72,363.93,253.53,313.20,271.07,267.45,280.90,268.27,2018,October
335,222.40,247.89,241.01,364.69,254.81,311.96,274.00,266.81,283.65,269.53,2018,November
336,223.57,247.43,242.25,366.27,257.16,313.61,274.84,268.06,283.08,270.47,2018,December
337,226.00,247.58,244.09,369.97,255.67,314.56,276.49,269.34,285.24,272.12,2019,January
338,227.35,251.03,241.24,368.29,258.40,315.22,277.61,269.83,286.41,272.83,2019,February

In [14]:
df

,East North Central (SA),East South Central (SA),Middle Atlantic (SA),Mountain (SA),New England (SA),Pacific (SA),South Atlantic (SA),West North Central (SA),West South Central (SA),USA (SA),Year,Month
1,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,1991,January
2,101.07,100.41,100.17,98.63,102.55,100.52,100.41,100.70,99.72,100.46,1991,February
3,101.00,100.60,99.74,100.54,101.44,100.13,100.60,100.14,100.55,100.50,1991,March
4,101.04,100.58,99.07,100.35,100.94,100.06,100.48,100.46,100.09,100.33,1991,April
5,101.43,100.77,99.12,100.39,99.81,100.11,100.57,100.24,100.35,100.41,1991,May
6,101.56,101.56,98.82,101.46,98.68,99.88,100.67,100.59,100.96,100.54,1991,June
7,101.94,101.57,99.06,101.27,98.76,99.85,100.47,100.46,100.83,100.56,1991,July
8,102.13,100.76,98.60,101.30,98.01,99.95,100.03,100.78,100.57,100.38,1991,August
9,102.06,101.18,99.25,101.55,99.15,99.63,100.11,100.90,101.46,100.64,1991,September
10,102.41,101.65,98.97,102.52,98.75,100.34,100.95,101.54,100.67,100.95,1991,October
11,103.37,102.37,100.05,103.82,97.45,100.60,101.33,101.59,101.35,101.49,1991,November
12,103.45,103.29,100.31,103.42,98.72,100.66,101.58,102.67,101.86,101.85,1991,December
13,103.95,103.35,100.70,104.41,99.85,100.97,101.91,102.48,102.40,102.26,1992,January
14,104.48,104.26,101.94,105.30,100.48,101.39,102.69,103.11,103.28,103.01,1992,February
15,105.21,103.99,101.18,106.01,99.44,100.79,102.33,103.68,102.51,102.82,1992,March
16,105.28,103.55,100.80,105.67,98.40,100.28,101.81,103.69,102.78,102.55,1992,April
17,105.64,104.02,100.36,106.29,97.60,100.25,102.05,103.95,102.62,102.63,1992,May
18,105.69,104.25,100.30,106.90,96.52,99.73,101.85,104.37,103.01,102.60,1992,June
19,106.04,104.92,100.26,107.18,96.77,100.01,102.27,104.82,103.28,102.91,1992,July
20,106.50,105.47,100.28,108.02,97.74,100.17,103.07,105.00,104.03,103.40,1992,August
21,106.79,106.01,101.20,108.41,97.65,100.26,103.59,105.56,104.19,103.79,1992,September
22,107.51,106.65,101.37,109.40,98.05,99.57,103.73,105.77,104.92,104.09,1992,October
23,107.91,106.40,102.12,110.07,98.55,99.64,103.53,106.15,105.62,104.39,1992,November
24,108.53,106.85,101.26,111.23,97.45,99.24,103.30,106.43,105.10,104.29,1992,December
25,108.62,107.10,100.91,112.00,96.69,98.73,103.37,107.48,105.38,104.34,1993,January
26,108.43,106.60,100.75,112.23,95.37,98.06,103.22,107.94,105.53,104.12,1993,February
27,108.98,108.07,100.64,112.53,95.45,98.32,103.76,106.97,106.16,104.46,1993,March
28,109.56,108.40,101.39,113.91,96.52,98.30,104.55,108.42,106.59,105.12,1993,April
29,109.91,108.87,101.69,114.79,96.16,97.91,104.51,109.07,107.06,105.32,1993,May
30,110.61,108.99,101.49,115.48,96.94,97.94,105.09,109.59,107.60,105.72,1993,June
...,...,...,...,...,...,...,...,...,...,...,...,...
309,196.32,216.57,215.58,304.08,226.53,267.84,237.67,236.73,251.34,235.52,2016,September
310,197.16,217.01,216.42,307.77,228.30,268.88,239.34,237.83,252.52,236.79,2016,October
311,198.12,219.07,218.68,308.51,229.52,271.33,240.43,238.98,253.62,238.23,2016,November
312,199.61,220.95,217.94,311.02,229.46,272.58,241.81,240.88,254.42,239.40,2016,December
313,199.55,219.04,218.13,310.97,230.58,273.89,242.35,239.94,255.72,239.66,2017,January
314,201.17,222.35,220.36,315.52,232.81,275.98,243.61,241.63,257.70,241.72,2017,February
315,202.79,223.91,220.12,317.04,234.46,278.86,245.12,243.71,257.21,243.05,2017,March
316,203.34,223.05,222.58,319.94,235.04,280.88,247.60,244.05,261.04,244.79,2017,April
317,203.85,223.73,222.28,321.29,234.83,283.41,248.20,246.03,262.83,245.77,2017,May
318,203.70,225.62,222.63,323.12,236.10,285.36,248.63,246.91,262.79,246.48,2017,June
319,205.63,227.54,224.42,326.07,237.76,285.33,250.63,246.89,264.09,248.00,2017,July
320,206.62,228.53,226.09,327.75,238.27,289.51,253.06,248.12,265.90,249.88,2017,August
321,207.73,228.31,227.44,330.85,239.14,291.34,253.21,249.77,267.41,251.02,2017,September
322,209.10,233.42,229.33,333.82,241.73,293.14,255.14,251.28,268.59,253.04,2017,October
323,210.33,230.26,229.14,338.10,241.93,295.43,256.82,252.72,270.97,254.29,2017,November
324,212.23,232.21,229.93,340.05,243.64,297.05,258.57,252.91,272.15,255.80,2017,December
325,214.18,234.29,231.30,342.82,244.75,300.72,261.20,256.24,270.50,257.74,2018,January
326,214.99,235.91,232.46,345.68,247.83,304.07,263.23,257.28,276.73,260.09,2018,February
327,215.27,235.65,236.38,348.32,245.87,303.95,264.04,258.77,274.79,260.67,2018,March
328,217.38,236.30,234.77,349.88,247.85,305.20,265.45,259.45,274.55,261.59,2018,April
329,216.80,238.93,234.88,352.21,249.00,305.59,266.87,260.61,276.95,262.58,2018,May
330,218.29,241.22,236.38,355.85,249.15,307.12,266.19,262.34,277.34,263.68,2018,June
331,219.36,240.96,237.51,355.49,249.07,308.82,269.05,263.45,277.73,264.87,2018,July
332,220.21,242.32,236.87,358.27,250.86,310.76,270.93,264.27,279.34,266.18,2018,August
333,221.81,242.64,237.78,362.62,251.75,308.92,271.75,264.03,280.25,266.95,2018,September
334,223.02,245.27,237.72,363.93,253.53,313.20,271.07,267.45,280.90,268.27,2018,October
335,222.40,247.89,241.01,364.69,254.81,311.96,274.00,266.81,283.65,269.53,2018,November
336,223.57,247.43,242.25,366.27,257.16,313.61,274.84,268.06,283.08,270.47,2018,December
337,226.00,247.58,244.09,369.97,255.67,314.56,276.49,269.34,285.24,272.12,2019,January
338,227.35,251.03,241.24,368.29,258.40,315.22,277.61,269.83,286.41,272.83,2019,February

In [15]:
df.to_csv("Clean Data/FHFACleaned.csv", index=False, header=True)